[tool.poetry]
name = "monitor"
version = "0.1.0"
description = ""
authors = ["Nik Cubrilovic <nc9@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
